# Generated by Django 5.2.5 on 2025-09-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="Nombre completo"),
                ),
                (
                    "document_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de documento"
                    ),
                ),
                (
                    "zone",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Zona"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Conductor",
                "verbose_name_plural": "Conductores",
                "ordering": ["full_name"],
            },
        ),
    ]
