# Generated by Django 5.2.5 on 2025-08-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='email',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='phone',
        ),
        migrations.AlterField(
            model_name='driver',
            name='document_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='zone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zona'),
        ),
    ]
