# render.yaml (versión alternativa más específica)

services:
  # El servicio web que correrá nuestra aplicación Django
  - type: web
    name: sigma-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
      python manage.py createsuperuser --noinput || true
    startCommand: gunicorn project.wsgi:application

databases:
  # La base de datos PostgreSQL
  - name: sigma-db
    type: postgres
    plan: free