# Generated by Django 5.2.5 on 2025-08-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0003_vehicle_current_zone_vehiclezonehistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="fuel_type",
            field=models.CharField(
                choices=[("GASOLINE", "Gasolina"), ("DIESEL", "Diésel")],
                default="DIESEL",
                max_length=20,
                verbose_name="Tipo de Combustible",
            ),
        ),
    ]
