# Generated by Django 5.2.5 on 2025-08-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_alter_vehicle_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(help_text='Ej: Camioneta, Bus, Automovil', max_length=50, verbose_name='Tipo de Vehículo'),
        ),
    ]
