# Generated by Django 5.2.5 on 2025-09-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0006_alter_vehicle_vehicle_type_fueluploadlog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicle",
            old_name="model",
            new_name="linea",
        ),
        migrations.RenameField(
            model_name="vehicle",
            old_name="year",
            new_name="modelo",
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="linea",
            field=models.CharField(max_length=50, verbose_name="Línea"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="modelo",
            field=models.PositiveIntegerField(verbose_name="Modelo"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.CharField(
                "Tipo de Vehículo",
                max_length=10,
                choices=[
                    ("AUTOMOVIL", "Automóvil"),
                    ("MICROBUS", "Microbús"),
                    ("BUS", "Bus"),
                ],
                help_text="Seleccione el tipo de vehículo",
            ),
        ),
    ]
