# Generated by Django 5.2.5 on 2025-09-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0007_rename_vehicle_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("AUTOMOVIL", "Automóvil"),
                    ("MICROBUS", "Microbús"),
                    ("BUS", "Bus"),
                    ("CAMION", "Camión"),
                    ("CAMIONETA", "Camioneta"),
                    ("TRACTOMULA", "Tractomula"),
                    ("MOTOCICLETA", "Motocicleta"),
                ],
                help_text="Seleccione el tipo de vehículo",
                max_length=50,
                verbose_name="Tipo de Vehículo",
            ),
        ),
    ]
