# Generated by Django 5.2.5 on 2025-09-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0007_rename_vehicle_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("AUTOMOVIL", "Automóvil"),
                    ("MICROBUS", "Microbús"),
                    ("BUS", "Bus"),
                    ("CAMIONETA", "Camioneta"),
                    ("BUSETA", "Buseta"),
                ],
                help_text="Seleccione el tipo de vehículo: Automóvil, Microbús, Bus, Camioneta o Buseta",
                max_length=20,
                verbose_name="Tipo de Vehículo",
            ),
        ),
    ]
