# Generated by Django 5.2.5 on 2025-08-27 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU (Referencia)')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Repuesto')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Ubicación en Bodega')),
                ('stock_current', models.PositiveIntegerField(default=0, verbose_name='Stock Actual')),
                ('stock_min', models.PositiveIntegerField(default=1, verbose_name='Stock Mínimo')),
                ('average_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Promedio')),
            ],
            options={
                'verbose_name': 'Repuesto',
                'verbose_name_plural': 'Repuestos',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del Proveedor')),
                ('nit', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='NIT')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Persona de Contacto')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('INBOUND', 'Entrada'), ('OUTBOUND', 'Salida'), ('ADJUSTMENT', 'Ajuste')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('reason', models.CharField(blank=True, help_text='Ej: Compra inicial, Consumo en OT, Ajuste por inventario físico', max_length=255, verbose_name='Motivo del movimiento')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorders.workorder', verbose_name='Orden de Trabajo')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.part', verbose_name='Repuesto')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
            },
        ),
        migrations.AddField(
            model_name='part',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier', verbose_name='Proveedor'),
        ),
    ]
