# Generated by Django 5.2.5 on 2025-08-28 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('size_bytes', models.BigIntegerField()),
                ('sheet_name', models.CharField(default='TANQUEOS', max_length=100)),
                ('rows_processed', models.PositiveIntegerField(default=0)),
                ('vehicles_updated', models.PositiveIntegerField(default=0)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_upload_logs_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
    ]
