# Generated by Django 5.2.5 on 2025-08-27 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('KM', 'Kilometraje'), ('TIME', 'Tiempo (días)'), ('HOURS', 'Horas de Motor')], max_length=10, verbose_name='Tipo de Plan')),
                ('threshold_value', models.PositiveIntegerField(help_text='Kilómetros, Días u Horas de motor para la próxima activación', verbose_name='Valor Umbral')),
                ('last_execution_value', models.PositiveIntegerField(default=0, help_text='Odómetro, fecha (en días) u horas en el último mantenimiento', verbose_name='Valor en Última Ejecución')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción del Plan')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='fleet.vehicle', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Plan de Mantenimiento',
                'verbose_name_plural': 'Planes de Mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('IN_PROGRESS', 'En Progreso'), ('WAITING_PART', 'En Espera de Repuesto'), ('COMPLETED', 'Completada'), ('VERIFIED', 'Verificada (Cerrada)'), ('CANCELLED', 'Cancelada')], default='OPEN', max_length=20, verbose_name='Estado')),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], default='MEDIUM', max_length=20, verbose_name='Prioridad')),
                ('description', models.TextField(verbose_name='Descripción del Problema/Trabajo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Apertura')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Mano de Obra')),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Repuestos')),
                ('assigned_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_ots', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Asignado')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.vehicle', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título de la Tarea')),
                ('hours_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Horas Invertidas')),
                ('evidence_url', models.URLField(blank=True, verbose_name='URL de Evidencia')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workorders.workorder', verbose_name='Orden de Trabajo')),
            ],
            options={
                'verbose_name': 'Tarea de OT',
                'verbose_name_plural': 'Tareas de OT',
            },
        ),
    ]
