# Generated by Django 5.2.5 on 2025-08-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0003_maintenancecategory_alter_maintenanceplan_grace_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceplan',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Plan 'dormido' hasta cerrar primera OT Preventiva", verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='maintenanceplan',
            name='last_service_km',
            field=models.PositiveIntegerField(default=0, help_text='Se actualiza al cerrar OT Preventiva', verbose_name='Km en Último Servicio'),
        ),
        migrations.AlterField(
            model_name='maintenanceplan',
            name='plan_type',
            field=models.CharField(choices=[('KM_TIME', 'Kilometraje (respaldo por tiempo)'), ('TIME', 'Solo por Tiempo (días)'), ('HOURS', 'Solo por Horas de Motor')], default='KM_TIME', max_length=10, verbose_name='Tipo de Plan'),
        ),
        migrations.AlterField(
            model_name='maintenanceplan',
            name='threshold_days',
            field=models.PositiveIntegerField(default=180, verbose_name='Umbral Tiempo (días)'),
        ),
        migrations.AlterField(
            model_name='maintenanceplan',
            name='threshold_km',
            field=models.PositiveIntegerField(default=10000, verbose_name='Umbral Kilometraje (km)'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='check_in_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ingreso Real'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='check_out_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Salida Real'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], default='MEDIUM', max_length=20, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Programada'), ('IN_RECEPTION', 'En Recepción'), ('IN_SERVICE', 'En Servicio'), ('WAITING_PART', 'Espera Repuesto'), ('PENDING_APPROVAL', 'Pendiente Aprobación'), ('STOPPED_BY_CLIENT', 'Detenida Cliente'), ('IN_ROAD_TEST', 'Prueba de Ruta'), ('COMPLETED', 'Completada'), ('VERIFIED', 'Verificada'), ('CANCELLED', 'Cancelada')], default='SCHEDULED', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='workorderpart',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Cantidad Usada'),
        ),
    ]
