# Generated by Django 5.2.5 on 2025-08-29 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_driver'),
        ('workorders', '0006_alter_maintenancemanual_fuel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderCorrective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_diagnosis', models.TextField(blank=True, verbose_name='Pre diagnóstico')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corrective', to='workorders.workorder')),
            ],
            options={
                'verbose_name': 'Datos de Correctivo',
                'verbose_name_plural': 'Datos de Correctivos',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderDriverAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('RESP', 'Responsable'), ('CORESP', 'Co-responsable')], default='RESP', max_length=10, verbose_name='Rol')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notas')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Asignado')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='users.driver')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignments', to='workorders.workorder')),
            ],
            options={
                'verbose_name': 'Conductor asignado',
                'verbose_name_plural': 'Conductores asignados',
                'ordering': ['-assigned_at'],
                'unique_together': {('work_order', 'driver')},
            },
        ),
    ]
