# Generated by Django 5.2.5 on 2025-08-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_driver'),
        ('workorders', '0007_workordercorrective_workorderdriverassignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workorderdriverassignment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='workorderdriverassignment',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='workorderdriverassignment',
            name='work_order',
        ),
        migrations.CreateModel(
            name='CorrectiveOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Orden de Trabajo Correctiva',
                'verbose_name_plural': 'Órdenes de Trabajo Correctivas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('workorders.workorder',),
        ),
        migrations.CreateModel(
            name='PreventiveOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Orden de Trabajo Preventiva',
                'verbose_name_plural': 'Órdenes de Trabajo Preventivas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('workorders.workorder',),
        ),
        migrations.AddField(
            model_name='workorder',
            name='drivers',
            field=models.ManyToManyField(blank=True, related_name='work_orders', to='users.driver', verbose_name='Conductores responsables'),
        ),
        migrations.DeleteModel(
            name='WorkOrderCorrective',
        ),
        migrations.DeleteModel(
            name='WorkOrderDriverAssignment',
        ),
    ]
