# Generated by Django 5.2.5 on 2025-08-29 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_active_driver_is_active_and_more'),
        ('workorders', '0008_alter_workorderdriverassignment_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbableCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Causa Probable',
                'verbose_name_plural': 'Causas Probables',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='failure_origin',
            field=models.CharField(blank=True, choices=[('MISUSE', 'Mal uso / Operación'), ('WEAR', 'Desgaste normal'), ('ROUTE', 'Condiciones de ruta'), ('MANUFACTURING', 'Falla de fabricación'), ('MAINTENANCE', 'Mantenimiento previo deficiente'), ('OTHER', 'Otro')], max_length=20, null=True, verbose_name='Origen de la falla'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='out_of_service',
            field=models.BooleanField(default=False, verbose_name='Vehículo fuera de servicio'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='pre_diagnosis',
            field=models.TextField(blank=True, verbose_name='Pre-diagnóstico'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='requires_approval',
            field=models.BooleanField(default=False, verbose_name='Requiere aprobación'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='severity',
            field=models.CharField(blank=True, choices=[('MINOR', 'Leve'), ('MODERATE', 'Moderada'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], max_length=12, null=True, verbose_name='Severidad'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='warranty_covered',
            field=models.BooleanField(default=False, verbose_name='Cubre garantía'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='probable_causes',
            field=models.ManyToManyField(blank=True, related_name='work_orders', to='workorders.probablecause', verbose_name='Causas probables'),
        ),
        migrations.CreateModel(
            name='WorkOrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='workorders.workorder')),
            ],
            options={
                'verbose_name': 'Adjunto de OT',
                'verbose_name_plural': 'Adjuntos de OT',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsibility_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Responsabilidad (%)')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order_links', to='users.driver')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_links', to='workorders.workorder')),
            ],
            options={
                'verbose_name': 'Responsable en OT',
                'verbose_name_plural': 'Responsables en OT',
                'unique_together': {('work_order', 'driver')},
            },
        ),
        # 🔧 En lugar de AlterField, hacemos RemoveField + AddField
        migrations.RemoveField(
            model_name='workorder',
            name='drivers',
        ),
        migrations.AddField(
            model_name='workorder',
            name='drivers',
            field=models.ManyToManyField(
                to='users.driver',
                related_name='work_orders',
                blank=True,
                through='workorders.workorderdriver',
                verbose_name='Conductores responsables',
            ),
        ),
        migrations.CreateModel(
            name='WorkOrderNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('ALL', 'Todos'), ('MGMT_ONLY', 'Solo Gerencia')], default='ALL', max_length=10, verbose_name='Visibilidad')),
                ('text', models.TextField(verbose_name='Comentario / Novedad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='workorders.workorder')),
            ],
            options={
                'verbose_name': 'Novedad de OT',
                'verbose_name_plural': 'Novedades de OT',
                'ordering': ['-created_at'],
            },
        ),
    ]
