# Generated by Django 5.2.5 on 2025-08-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_driver'),
        ('workorders', '0009_probablecause_workorder_failure_origin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CorrectiveOrder',
        ),
        migrations.DeleteModel(
            name='PreventiveOrder',
        ),
        migrations.AlterField(
            model_name='workorder',
            name='drivers',
            field=models.ManyToManyField(blank=True, related_name='work_orders', through='workorders.WorkOrderDriver', to='users.driver', verbose_name='Conductores responsables'),
        ),
    ]
