# Generated by Django 5.2.5 on 2025-09-01 16:32

from django.db import migrations, models


def map_old_statuses(apps, schema_editor):
    WorkOrder = apps.get_model("workorders", "WorkOrder")
    mapping = {
        "IN_RECEPTION": "SCHEDULED",
        "IN_SERVICE": "SCHEDULED",
        "PENDING_APPROVAL": "SCHEDULED",
        "STOPPED_BY_CLIENT": "SCHEDULED",
        "VERIFIED": "COMPLETED",
        "CANCELLED": "COMPLETED",
    }
    for old, new in mapping.items():
        WorkOrder.objects.filter(status=old).update(status=new)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0010_delete_correctiveorder_delete_preventiveorder_and_more"),
    ]

    operations = [
        migrations.RunPython(map_old_statuses, noop),
        migrations.AlterField(
            model_name="workorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Programada"),
                    ("WAITING_PART", "Espera Repuesto"),
                    ("IN_ROAD_TEST", "Prueba de Ruta"),
                    ("COMPLETED", "Completada"),
                ],
                default="SCHEDULED",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
    ]
