# Generated by Django 5.2.5 on 2025-08-29 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0010_delete_correctiveorder_delete_preventiveorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderTaskEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Sube imagen o video como evidencia', upload_to='workorder_evidences/%Y/%m/', verbose_name='Archivo')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='workorders.workordertask', verbose_name='Trabajo')),
            ],
            options={
                'verbose_name': 'Evidencia de Trabajo',
                'verbose_name_plural': 'Evidencias de Trabajo',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
