# Generated by Django 5.2.5 on 2025-09-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0011_alter_workorder_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Programada"),
                    ("WAITING_PART", "Espera Repuesto"),
                    ("IN_PROGRESS", "En progreso"),
                    ("IN_ROAD_TEST", "Prueba de Ruta"),
                    ("COMPLETED", "Completada"),
                ],
                default="SCHEDULED",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
    ]
